GET http://localhost:8000/tracks/single?name=sine_48_og
###

GET http://localhost:8000/tracks/stream/lossy?name=sine_48_og
###

GET http://localhost:8000/tracks/stream/lossless?name=sine_48_og
###

GET http://localhost:8000/tracks/newest
###

POST http://localhost:8000/tracks/new
Content-Type: application/json

{
  "name": "nate_data1",
  "length": "00:02:07",
  "lossless": {
    "size": "91 MB",
    "sample_rate": 96000,
    "bit_rate": "6144kbps",
    "bit_depth": "32 bit",
    "file_path": "file_store/wav/nate_data1.wav"
  },
  "lossy": {
    "size": "1.89 MB",
    "sample_rate": 48000,
    "bit_rate": "124kbps",
    "file_path": "file_store/mp3/nate_data1.mp3"
  }
}
###
